#spring:
#  application:
#    name: task-service
#
#server:
#  port: 8503
#
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://192.168.32.38:8761/eureka/
#  instance:
#    hostname: localhost