// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ansible.proto

package com.netbrain.rpc.ansible;

public final class AnsibleProto {
  private AnsibleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netbrain_rpc_ansible_AnsibleJob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netbrain_rpc_ansible_AnsibleJob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rAnsible.proto\022\030com.netbrain.rpc.ansibl" +
      "e\"&\n\nAnsibleJob\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\t\"\226\001\n\022AnsibleJobResponse\022\017\n\007message\030\001 \001(" +
      "\t\0223\n\006status\030\002 \001(\0162#.com.netbrain.rpc.ans" +
      "ible.JobStatus\022:\n\013jobPriority\030\003 \001(\0162%.co" +
      "m.netbrain.rpc.ansible.JobPriority*>\n\tJo" +
      "bStatus\022\013\n\007Pending\020\000\022\013\n\007Running\020\001\022\013\n\007Suc" +
      "cess\020\002\022\n\n\006Failed\020\003*C\n\013JobPriority\022\007\n\003Low" +
      "\020\000\022\n\n\006Normal\020\001\022\010\n\004High\020\002\022\n\n\006Higher\020\003\022\t\n\005" +
      "Super\020\0042\177\n\017AnsibleExecutor\022l\n\022StartAutoM",
      "ationJob\022$.com.netbrain.rpc.ansible.Ansi" +
      "bleJob\032,.com.netbrain.rpc.ansible.Ansibl" +
      "eJobResponse\"\0000\001B*\n\030com.netbrain.rpc.ans" +
      "ibleB\014AnsibleProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_netbrain_rpc_ansible_AnsibleJob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netbrain_rpc_ansible_AnsibleJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netbrain_rpc_ansible_AnsibleJob_descriptor,
        new String[] { "Id", "Name", });
    internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_descriptor,
        new String[] { "Message", "Status", "JobPriority", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
