// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ansible.proto

package com.netbrain.rpc.ansible;

public interface AnsibleJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netbrain.rpc.ansible.AnsibleJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
   */
  JobStatus getStatus();

  /**
   * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
   */
  int getJobPriorityValue();
  /**
   * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
   */
  JobPriority getJobPriority();
}
