// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ansible.proto

package com.netbrain.rpc.ansible;

/**
 * Protobuf type {@code com.netbrain.rpc.ansible.AnsibleJobResponse}
 */
public  final class AnsibleJobResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.netbrain.rpc.ansible.AnsibleJobResponse)
        AnsibleJobResponseOrBuilder {
  // Use AnsibleJobResponse.newBuilder() to construct.
  private AnsibleJobResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnsibleJobResponse() {
    message_ = "";
    status_ = 0;
    jobPriority_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AnsibleJobResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            jobPriority_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AnsibleProto.internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AnsibleProto.internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AnsibleJobResponse.class, AnsibleJobResponse.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  private volatile Object message_;
  /**
   * <code>string message = 1;</code>
   */
  public String getMessage() {
    Object ref = message_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    Object ref = message_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
   */
  public JobStatus getStatus() {
    JobStatus result = JobStatus.valueOf(status_);
    return result == null ? JobStatus.UNRECOGNIZED : result;
  }

  public static final int JOBPRIORITY_FIELD_NUMBER = 3;
  private int jobPriority_;
  /**
   * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
   */
  public int getJobPriorityValue() {
    return jobPriority_;
  }
  /**
   * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
   */
  public JobPriority getJobPriority() {
    JobPriority result = JobPriority.valueOf(jobPriority_);
    return result == null ? JobPriority.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (status_ != JobStatus.Pending.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (jobPriority_ != JobPriority.Low.getNumber()) {
      output.writeEnum(3, jobPriority_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (status_ != JobStatus.Pending.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (jobPriority_ != JobPriority.Low.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, jobPriority_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AnsibleJobResponse)) {
      return super.equals(obj);
    }
    AnsibleJobResponse other = (AnsibleJobResponse) obj;

    boolean result = true;
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && status_ == other.status_;
    result = result && jobPriority_ == other.jobPriority_;
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + JOBPRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + jobPriority_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AnsibleJobResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnsibleJobResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnsibleJobResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnsibleJobResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnsibleJobResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnsibleJobResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnsibleJobResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AnsibleJobResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AnsibleJobResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AnsibleJobResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AnsibleJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AnsibleJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AnsibleJobResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.netbrain.rpc.ansible.AnsibleJobResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.netbrain.rpc.ansible.AnsibleJobResponse)
          AnsibleJobResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnsibleProto.internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnsibleProto.internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnsibleJobResponse.class, AnsibleJobResponse.Builder.class);
    }

    // Construct using com.netbrain.rpc.ansible.AnsibleJobResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      message_ = "";

      status_ = 0;

      jobPriority_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AnsibleProto.internal_static_com_netbrain_rpc_ansible_AnsibleJobResponse_descriptor;
    }

    public AnsibleJobResponse getDefaultInstanceForType() {
      return AnsibleJobResponse.getDefaultInstance();
    }

    public AnsibleJobResponse build() {
      AnsibleJobResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AnsibleJobResponse buildPartial() {
      AnsibleJobResponse result = new AnsibleJobResponse(this);
      result.message_ = message_;
      result.status_ = status_;
      result.jobPriority_ = jobPriority_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AnsibleJobResponse) {
        return mergeFrom((AnsibleJobResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AnsibleJobResponse other) {
      if (other == AnsibleJobResponse.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.jobPriority_ != 0) {
        setJobPriorityValue(other.getJobPriorityValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AnsibleJobResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AnsibleJobResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object message_ = "";
    /**
     * <code>string message = 1;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public Builder setMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     */
    public Builder clearMessage() {

      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      message_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
     */
    public JobStatus getStatus() {
      JobStatus result = JobStatus.valueOf(status_);
      return result == null ? JobStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
     */
    public Builder setStatus(JobStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }

      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobStatus status = 2;</code>
     */
    public Builder clearStatus() {

      status_ = 0;
      onChanged();
      return this;
    }

    private int jobPriority_ = 0;
    /**
     * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
     */
    public int getJobPriorityValue() {
      return jobPriority_;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
     */
    public Builder setJobPriorityValue(int value) {
      jobPriority_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
     */
    public JobPriority getJobPriority() {
      JobPriority result = JobPriority.valueOf(jobPriority_);
      return result == null ? JobPriority.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
     */
    public Builder setJobPriority(JobPriority value) {
      if (value == null) {
        throw new NullPointerException();
      }

      jobPriority_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.netbrain.rpc.ansible.JobPriority jobPriority = 3;</code>
     */
    public Builder clearJobPriority() {

      jobPriority_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.netbrain.rpc.ansible.AnsibleJobResponse)
  }

  // @@protoc_insertion_point(class_scope:com.netbrain.rpc.ansible.AnsibleJobResponse)
  private static final AnsibleJobResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AnsibleJobResponse();
  }

  public static AnsibleJobResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnsibleJobResponse>
      PARSER = new com.google.protobuf.AbstractParser<AnsibleJobResponse>() {
    public AnsibleJobResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnsibleJobResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnsibleJobResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AnsibleJobResponse> getParserForType() {
    return PARSER;
  }

  public AnsibleJobResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

