// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ansible.proto

package com.netbrain.rpc.ansible;

public interface AnsibleJobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netbrain.rpc.ansible.AnsibleJob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
