// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ansible.proto

package com.netbrain.rpc.ansible;

/**
 * Protobuf enum {@code com.netbrain.rpc.ansible.JobStatus}
 */
public enum JobStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Pending = 0;</code>
   */
  Pending(0),
  /**
   * <code>Running = 1;</code>
   */
  Running(1),
  /**
   * <code>Success = 2;</code>
   */
  Success(2),
  /**
   * <code>Failed = 3;</code>
   */
  Failed(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Pending = 0;</code>
   */
  public static final int Pending_VALUE = 0;
  /**
   * <code>Running = 1;</code>
   */
  public static final int Running_VALUE = 1;
  /**
   * <code>Success = 2;</code>
   */
  public static final int Success_VALUE = 2;
  /**
   * <code>Failed = 3;</code>
   */
  public static final int Failed_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static JobStatus valueOf(int value) {
    return forNumber(value);
  }

  public static JobStatus forNumber(int value) {
    switch (value) {
      case 0: return Pending;
      case 1: return Running;
      case 2: return Success;
      case 3: return Failed;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JobStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
          JobStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JobStatus>() {
          public JobStatus findValueByNumber(int number) {
            return JobStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return AnsibleProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final JobStatus[] VALUES = values();

  public static JobStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JobStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.netbrain.rpc.ansible.JobStatus)
}

